language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server
  - mysql

before_script:
  - "mysql -e 'create database `sspanel`;'"
  - mysql -uroot -p"" sspanel < db-160409.sql
  - cp .env.testing .env
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then composer require satooshi/php-coveralls:dev-master squizlabs/php_codesniffer:2.* -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then composer install -n ; fi

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then mkdir -p build/logs && phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then phpunit ; fi
after_script:
